# --- Site ---
title: LinuxWire Blog
email: staffordacademia@pm.me
description: >-
  I am a 20 year student majoring in interdisciplinary mathematical sciences and minoring in data sciences. 
url: "https://linuxwire.net"
baseurl: ""               # keep empty for root-domain deploy
github_username: linuxwire-blog
timezone: America/New_York
future: true

# --- Theme ---
theme: jekyll-theme-clean-blog

# --- Plugins (GitHub Pages compatible) ---
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Optional: site-wide fallback hero image (store it once)
hero_image: /assets/images/qcbackground.jpg

# --- Layout defaults ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      header-img: /assets/images/qcbackground.jpg   # <-- literal path, no Liquid
      background: /assets/images/qcbackground.jpg 
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      header-img: /assets/images/qcbackground.jpg
      background: /assets/images/qcbackground.jpg 

# --- Permalinks ---
permalink: /:categories/:year/:month/:day/:title/
